### ISSUE TITLE
Proposal: Retweet author tweets

### ISSUE THREAD

**Issue by wezm** [wezm/read-rust#41]
I’m proposing changing the behaviour of the Read Rust Twitter account to retweet author tweets when they can be found instead of creating a new tweet from @readrust.
 
The primary motivation for this change is to boost the authors voice. This would also make it easier for followers to like or reply to the original author on Twitter. Additionally there is some overlap in the posts shared on the official Rust account and the Read Rust account. Retweets would ensure you were only shown a tweet once if you follow both accounts. 
 
The main downside of this change is that the tweets from the Read Rust account would no longer all follow the same structure: "Title by Author #category #hashtags".

As an example for this post:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Rust review: The match keyword by Julio Merino: <a href="https://t.co/nRKCm2Mk7u">https://t.co/nRKCm2Mk7u</a> <a href="https://twitter.com/hashtag/language?src=hash&amp;ref_src=twsrc%5Etfw">#language</a></p>&mdash; Read Rust (@read_rust) <a href="https://twitter.com/read_rust/status/1009010498195427328?ref_src=twsrc%5Etfw">June 19, 2018</a></blockquote>

I would have retweeted this one instead:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Rust&#39;s match and pattern matching is something that should exist in other languages... aka the topic for today&#39;s part of my Rust review! <a href="https://t.co/AWVW1gYMBK">https://t.co/AWVW1gYMBK</a></p>&mdash; Julio Merino (@jmmv) <a href="https://twitter.com/jmmv/status/1007638228097208321?ref_src=twsrc%5Etfw">June 15, 2018</a></blockquote>

**Comment by sunjay** [comment]
I think this is a great idea. One way to implement it would be to allow users to add a link to a tweet they would like retweeted in their submission. (Maybe this is already what you had in mind, but I read it as if you would do it automatically by searching their profile or something.)

You could modify the submission template to allow users to optionally provide a link to a tweet which would be used instead of the default Read Rust tweet. Restrictions could be added to enforce that the tweet actually contains a link to the article, etc. 

A big benefit to this is that it allows authors to choose not only which tweet they want amplified, but also when they want their tweet amplified at all. It is completely opt-in and up to the author to decide when they want this and when they just want the regular Read Rust tweet.

**Comment by wezm** [comment]
> One way to implement it would be to allow users to add a link to a tweet they would like retweeted in their submission

That would be great but no one submits posts :) I will add it to the issue template though.

**Comment by bitshifter** [comment]
Could you retweet as a quote and keep the hashtags?

**Comment by wezm** [comment]
> Could you retweet as a quote and keep the hashtags?

Hmm that's an interesting way to keep them. Downside is you wouldn't get the de-duplication that you get with retweets.

**Comment by obust** [comment]
One way to submit posts could be to tag @read_rust or #read_rust at the end of the author's tweet. It would be request for retweet :P

>     Rust's match and pattern matching is something that should exist in other languages... aka the > topic for today's part of my Rust review! https://t.co/AWVW1gYMBK @read_rust
>     — Julio Merino (@jmmv) June 15, 2018
