### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by amitayadav** [wezm/read-rust#58]
Please add this post: How to upload any file on Amazon S3 using Rust? 

**Post URL:**  https://blog.knoldus.com/how-to-upload-any-file-on-amazon-s3-using-rust/
**Blog Homepage:** https://blog.knoldus.com/
**Author Name:** Amita Yadav, Knoldus Inc.
**Categories:** : Getting Started, Language, Web and Network Services

**Comment by wezm** [comment]
Thank you for submitting your post. Unfortunately I've decided to not to post it to Read Rust at this time. For a tutorial style post I would suggest the following in order to make it more suitable for publishing on Read Rust:

- All code examples are text to allow easy copying
- Downloadable code or source repository of a complete example that people can explore and run to follow along themselves.
